title: Max Baylis

permalink: /writing/:title
redirects: yes

markdown: kramdown
highlighter: rouge

remote_theme: mikeecb/cypher-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-redirect-from
exclude: [vendor]